"""
core/neuroml_export.py — NeuroML 2.x export utility (Stage 6.4)

Exports FullModelConfig as NeuroML 2.2 XML for interoperability with
NEURON, Brian2, and jNeuroML. Produces valid Level-1 NeuroML2 (neuroml.xsd).

References:
  - NeuroML v2.2 specification: https://neuroml.org/neuromlv2
  - Cannon et al. 2014, Front Neuroinform 8:79
"""

import xml.etree.ElementTree as ET
from xml.dom import minidom
from typing import Optional


def export_neuroml(cfg, path: Optional[str] = None) -> str:
    """Serialise *cfg* (FullModelConfig) to NeuroML 2.2 XML.

    Parameters
    ----------
    cfg : FullModelConfig
        Simulation configuration to export.
    path : str, optional
        File path to write. If None, returns the XML string only.

    Returns
    -------
    str
        Formatted NeuroML 2.2 XML string.
    """
    ch = cfg.channels
    mc = cfg.morphology
    env = cfg.env
    stim = cfg.stim

    # ── Root element ────────────────────────────────────────────────
    root = ET.Element("neuroml")
    root.set("xmlns", "http://www.neuroml.org/schema/neuroml2")
    root.set(
        "xmlns:xsi",
        "http://www.w3.org/2001/XMLSchema-instance",
    )
    root.set(
        "xsi:schemaLocation",
        "http://www.neuroml.org/schema/neuroml2 "
        "https://raw.github.com/NeuroML/NeuroML2/development/Schemas/NeuroML2/NeuroML_v2.2.xsd",
    )
    root.set("id", "NeuroModelPort_Export")

    # ── Metadata ────────────────────────────────────────────────────
    notes = ET.SubElement(root, "notes")
    notes.text = (
        "Auto-generated by NeuroModelPort (Stage 6.4 — NeuroML export). "
        f"Preset: {getattr(ch, '_preset_name', 'custom')}. "
        f"T = {env.T_celsius:.1f}°C."
    )

    # ── Ion channel definitions ──────────────────────────────────────
    _add_ion_channel(root, "na_hh",  "na",  "nS",
                     desc="Hodgkin-Huxley Na channel (Hodgkin & Huxley 1952)")
    _add_ion_channel(root, "k_hh",   "k",   "nS",
                     desc="Hodgkin-Huxley delayed-rectifier K channel")
    _add_ion_channel(root, "leak_hh","non_specific", "nS",
                     desc="Hodgkin-Huxley leak conductance")

    if ch.enable_Ih:
        _add_ion_channel(root, "ih_hcn", "non_specific", "nS",
                         desc="HCN channel Ih (Magee 1998)")
    if ch.enable_ICa:
        _add_ion_channel(root, "ica_ltype", "calcium", "nS",
                         desc="L-type Ca2+ channel")
    if ch.enable_IA:
        _add_ion_channel(root, "ia_transient", "potassium", "nS",
                         desc="Transient A-type K+ (Huguenard 1991)")
    if ch.enable_SK:
        _add_ion_channel(root, "sk_ca_activated", "potassium", "nS",
                         desc="SK Ca2+-activated K+ (Hirschberg 1998)")
    if ch.enable_ITCa:
        _add_ion_channel(root, "itca_ttype", "calcium", "nS",
                         desc="T-type low-threshold Ca2+ CaV3.x (Destexhe 1998)")
    if ch.enable_IM:
        _add_ion_channel(root, "im_mtype", "potassium", "nS",
                         desc="M-type K+ KCNQ2/3 (Yamada 1989)")
    if ch.enable_NaP:
        _add_ion_channel(root, "nap_persistent", "sodium", "nS",
                         desc="Persistent Na+ (Magistretti & Alonso 1999)")
    if ch.enable_NaR:
        _add_ion_channel(root, "nar_resurgent", "sodium", "nS",
                         desc="Resurgent Na+ (Raman & Bean 2001)")

    # ── Cell definition ─────────────────────────────────────────────
    cell = ET.SubElement(root, "cell")
    cell.set("id", "NeuroModelPort_cell")

    morphology = ET.SubElement(cell, "morphology")
    morphology.set("id", "morphology")

    # Soma segment
    seg_soma = ET.SubElement(morphology, "segment")
    seg_soma.set("id", "0")
    seg_soma.set("name", "soma")
    d_soma_um = mc.d_soma * 1e4  # cm → µm
    prox = ET.SubElement(seg_soma, "proximal")
    prox.set("x", "0"); prox.set("y", "0"); prox.set("z", "0")
    prox.set("diameter", f"{d_soma_um:.3f}")
    dist = ET.SubElement(seg_soma, "distal")
    dist.set("x", "0"); dist.set("y", "0"); dist.set("z", f"{d_soma_um:.3f}")
    dist.set("diameter", f"{d_soma_um:.3f}")

    # AIS segments (simplified as a single cable segment)
    if not mc.single_comp and mc.N_ais > 0:
        seg_ais = ET.SubElement(morphology, "segment")
        seg_ais.set("id", "1")
        seg_ais.set("name", "axon_initial_segment")
        seg_ais.set("parent", "0")
        d_ais_um = mc.d_ais * 1e4
        l_ais_um = mc.l_ais * 1e4 * mc.N_ais
        p_ais = ET.SubElement(seg_ais, "proximal")
        p_ais.set("x", "0"); p_ais.set("y", "0"); p_ais.set("z", f"{d_soma_um:.3f}")
        p_ais.set("diameter", f"{d_ais_um:.3f}")
        d_ais = ET.SubElement(seg_ais, "distal")
        d_ais.set("x", "0"); d_ais.set("y", "0"); d_ais.set("z", f"{d_soma_um + l_ais_um:.3f}")
        d_ais.set("diameter", f"{d_ais_um:.3f}")

    # Biophysical properties
    biophys = ET.SubElement(cell, "biophysicalProperties")
    biophys.set("id", "biophys")

    membrane = ET.SubElement(biophys, "membraneProperties")

    # Capacitance
    cap = ET.SubElement(membrane, "specificCapacitance")
    cap.set("value", f"{ch.Cm:.3f} uF_per_cm2")

    # Reversal potentials
    _add_reversal(membrane, "na",          ch.ENa)
    _add_reversal(membrane, "k",           ch.EK)
    _add_reversal(membrane, "non_specific", ch.EL)
    if ch.enable_Ih:
        _add_reversal(membrane, "non_specific_ih", ch.E_Ih)
    if ch.enable_ICa or ch.enable_ITCa:
        _add_reversal(membrane, "ca",      ch.E_Ca)

    # Channel densities (all-compartment uniform; single-compartment model)
    _add_channel_density(membrane, "na_hh_soma",   "na_hh",  ch.gNa_max, "na",
                         segment_group="soma_group")
    _add_channel_density(membrane, "k_hh_soma",    "k_hh",   ch.gK_max,  "k",
                         segment_group="soma_group")
    _add_channel_density(membrane, "leak_hh_soma", "leak_hh", ch.gL, "non_specific",
                         segment_group="soma_group")

    if ch.enable_Ih:
        _add_channel_density(membrane, "ih_soma", "ih_hcn", ch.gIh_max, "hcn",
                             segment_group="soma_group")
    if ch.enable_ICa:
        _add_channel_density(membrane, "ica_soma", "ica_ltype", ch.gCa_max, "ca",
                             segment_group="soma_group")
    if ch.enable_IA:
        _add_channel_density(membrane, "ia_soma", "ia_transient", ch.gA_max, "k",
                             segment_group="soma_group")
    if ch.enable_SK:
        _add_channel_density(membrane, "sk_soma", "sk_ca_activated", ch.gSK_max, "k",
                             segment_group="soma_group")
    if ch.enable_ITCa:
        _add_channel_density(membrane, "itca_soma", "itca_ttype", ch.gTCa_max, "ca",
                             segment_group="soma_group")
    if ch.enable_IM:
        _add_channel_density(membrane, "im_soma", "im_mtype", ch.gIM_max, "k",
                             segment_group="soma_group")
    if ch.enable_NaP:
        _add_channel_density(membrane, "nap_soma", "nap_persistent", ch.gNaP_max, "na",
                             segment_group="soma_group")
    if ch.enable_NaR:
        _add_channel_density(membrane, "nar_soma", "nar_resurgent", ch.gNaR_max, "na",
                             segment_group="soma_group")

    # Intracellular properties
    intra = ET.SubElement(biophys, "intracellularProperties")
    ra = ET.SubElement(intra, "resistivity")
    ra.set("value", f"{mc.Ra:.1f} ohm_cm")

    # ── Stimulus (PulseGenerator) ────────────────────────────────────
    if stim.stim_type in ("const", "pulse"):
        pg = ET.SubElement(root, "pulseGenerator")
        pg.set("id", "stim0")
        pg.set("delay",    f"{stim.pulse_start:.3f}ms")
        dur_ms = stim.pulse_dur if stim.stim_type == "pulse" else f"{stim.t_sim:.3f}"
        pg.set("duration", f"{dur_ms}ms")
        pg.set("amplitude", f"{stim.Iext:.4f}uA_per_cm2")

    # ── Simulation specification ─────────────────────────────────────
    sim = ET.SubElement(root, "Simulation")
    sim.set("id", "sim0")
    sim.set("length",    f"{stim.t_sim:.3f}ms")
    sim.set("step",      f"{stim.dt_eval:.5f}ms")
    sim.set("target",    "net0")
    sim.set("temperature", f"{env.T_celsius:.1f}degC")

    # ── Format & return ─────────────────────────────────────────────
    xml_str = minidom.parseString(ET.tostring(root, encoding="unicode")).toprettyxml(
        indent="    ", encoding=None
    )
    # Remove the redundant <?xml?> declaration that toprettyxml adds
    lines = xml_str.split("\n")
    if lines[0].startswith("<?xml"):
        xml_str = "\n".join(lines[1:])
    xml_str = '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_str

    if path is not None:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(xml_str)

    return xml_str


# ── Private helpers ──────────────────────────────────────────────────

def _add_ion_channel(parent, channel_id: str, species: str, conductance_units: str,
                     desc: str = ""):
    el = ET.SubElement(parent, "ionChannel")
    el.set("id", channel_id)
    el.set("species", species)
    el.set("conductance", f"10 {conductance_units}")  # placeholder; actual density set in cell
    if desc:
        notes = ET.SubElement(el, "notes")
        notes.text = desc


def _add_reversal(parent, ion: str, value_mV: float):
    er = ET.SubElement(parent, "reversalPotential")
    er.set("species", ion)
    er.set("value", f"{value_mV:.2f}mV")


def _add_channel_density(parent, density_id: str, channel_id: str,
                         g_max: float, ion: str, segment_group: str = "all"):
    cd = ET.SubElement(parent, "channelDensity")
    cd.set("id", density_id)
    cd.set("ionChannel", channel_id)
    # NeuroML uses S_per_m2; g_max here is in mS/cm² → × 10 = S/m²
    g_si = g_max * 10.0
    cd.set("condDensity", f"{g_si:.4f} S_per_m2")
    cd.set("erev", f"0.0mV")   # placeholder; actual erev set in reversalPotential
    cd.set("ion", ion)
    cd.set("segmentGroup", segment_group)
